# .slather.yml
#
coverage_service: coveralls
xcodeproj: Example/KVOMutableArray.xcodeproj
workspace: Example/KVOMutableArray.xcworkspace
scheme: KVOMutableArray-Example 
source_directory: Pod/Classes

# if you want to invoke slather on the local machine
# gem i slather
# slather coverage -s --scheme KVOMutableArray-Example --workspace ./Example/KVOMutableArray.xcworkspace ./Example/KVOMutableArray.xcodeproj
