# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - rvm use system # see https://github.com/CocoaPods/CocoaPods/issues/4711
  - "brew uninstall xctool; brew install xctool --HEAD;"
  - gem install cocoapods slather --user-install --bindir ~/bin --no-ri --no-rdoc --no-document --quiet
xcode_workspace: Example/KVOMutableArray.xcworkspace
xcode_scheme: KVOMutableArray-Example
xcode_sdk: iphonesimulator
after_success: slather
